engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    exclude_paths:
    - "coverage/"
    - "dist/"
    - "manual/"
    - "node_modules/"
    - "test/"
    - "test2/"
ratings:
  paths:
  - src/**
  - test/**
