language: node_js
node_js:
- '8'
env:
  secure: leHNOaVesfD89PTvxLtQX5ZdGvi4LFwnVa/SbMmdfsGMni6ZV88fj1xFPqaV9iRkqVCH2GonBq5hyQdSiG3VLS5Qb31h0zyRo5lZ/bFIvKp4d3t9nekkFr+UrN4q8ZZt8GSjGFUppCrC0Ml2IgkgR2SgtJU51yvXBFDbKXbsTp56fkw5XPCucouXnfsiq3IaefBMp898sqrFYKZL0a5MzVBeRurUW3ikWjjWCCwVIT4Uk6hT4AX6AVkTjmumOzDCk9KnbUhz7o793XisQPfMZ3uZy8j9NzWjGVDoX2vcWZkGaFVdDaid3wc+KN67RmyMFNoRIqd3XaVWVQbhqjYQjQ4Nvp8tS6HxDafcKTYidZHFg2hmm46LP4z1G+XfTOiOmAp9TKgO5/eujUkS3cTO7Fl0mS0ddK/r6I9SsHnBXrAmODRUoCDS0LEVk5rn2JawQFsEWJtck2lpOZe4UZJQ7+oWHOTnXFOjzSe7+ZZRe5jwDEt+goQ1DH1EVLAm96q6vCnFCPKUa1V0bvm1YcgoU16pRos0BvqvH9hJjvXouxZ96lxkcmEPTiIlb88qGSk2LZTXkuy8YI3kvLO/I926r9BFFockMC4xDhhpv1Cc9+M8JxClXut2p8KQYijG0re4iVpjFgKUR/R+9kmvHysznS/W5/HLSqObkGoQbZdbGC8=
script:
- npm run ci
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: thomas.conner@me.com
  api_key:
    secure: zs64wz+OIVD9gKu2qZ+zjDJZsFqBPAM0umhYxdCXvBPfxPnHiy5CYJJWhzi8E/bY9o5jfPRc04OFWcKRYVI0k65fCImpnuettO/ADXJ1fB/9H7YuKyNz/TwFsehmbRiiyyqRQn4neIrXs0ewxZFoh/4+HBN29PCrTj5s2o5Xt+c+44ijON2hpSFZA8emTLscdL0shuWHOv9PCxbfm6E/eBrC0/NW3pWQDOCDFJX7ZQzYX8M3DmSwKyf1U7XOLlUAwZ0FmmncXHrzDGRL2hypbOLae6sY3b34/cE+zi/CGoot5k4QvTrAQewX6ufwu2iAxSU8Fq4zF0Qb1Ry4T20j2XB9IBzEc79nHJT20naBAtZVJ5eKPCeU1yzoWJbM51lAUm2SGzNU3dQue6P71r/PsKD4oJLT2SdGHi+uq492SWWnBN8EJU0w82q1/UnKpUPMazN+lYGNmxCXeQbm5MLOJ0g783LH2XV6vOaESr97B3tNkE30krrwCH148UVcHkBOhkY5U8vwMp+EKv4IFTGZmoBylUMAHCpr7XrYRubHPseFva+pCTd4BfhhEZx8F1ikzC0rbN4/X0yGOnumKbH5s1QL9iU/AvSksyLLEnTQ5ZlCS1yaB02MBt8jK19VT1WWZc66QGpwDsgOSMyvN6Wyju1zpD1clYEEbqIwZgs9kR0=
  on:
    tags: true
    repo: Kinvey/js-sdk
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    secure: zhQEKSmoMrI5yj180Z8NtAqujmMgRI3TIO/DrnFEDjuXziBanKr2Thnzup0Gmr5vfOA1c3yh/HVs671188UDsE6YSf/r8ephjE+dzlk3iyYE6ViHUHB7ju+DKyGOeNPk8yMFUqDhLhtQ9wA8Bvlzbfn/ZwPk2ArDZgp3ixBEmIzB/gkcq4EC+2ciJbBUh99fOPUYspvAvf4xLlQRPNiuZ/BSCfeASRkvYdUp9kAMZecIt2EfAneTAOyEBKc+8ob24Yu5L8GfSnNa8qeAmzwki6WGaVR7EantJ0SA/dXyISlj08ckW/MEY5hoBhy1x0/gsaPaLNfq/GRz1Zj69Qmqz359tknuRBC4lMmEyutG9SKNBB8OAtNyUUnnNi45P+fyTUP/4l+4tYEN4hj/ncnFKvW5P5ls/LZ84wpjfAiUlkVqSwKXUnzccYDYNBfeVMEpTwoxctBgRp9Akalf3nVYfZHvH+/Sy3VGzDqagF+55+kTgfPmf763lKbOanr2HNzpvIfT21UyZ2EEDAoAkqr65HbA+yYgs/Awni02qzalafmIbP3aF9a3yULftubAvfsKALjrde38iqE5kOvsyiFOjescA7chdpJqudn6sT6SuYHaVoaBzqKX0t2aLWq8a9rMoS1qKW22IQ2CQilAtVG5Nb19mcUSjkisoIYnrCvK700=
