language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: rjjif72hEKA0D2P79PzZYYZDmnyHBSVZo7k3gRQtRp6T0EQ5h06Z0orbSYNF94JgL1gca6vxANzuitWJllN44e9Dsnt+jnNjnPw0/MtpOGnsP3DSBxe6C0/ltMeCAlYcCmvbdp6SXlFNABXvWRiNQd3rtFePwBtNbASixZB3T26vZ9UqFoVoGtONHgI8CkABv4a0tUU2p8i+zloegbIVwUvI9Vr2gV/zWqviHrcirwao19IvbcCJmOJssDC7iU+tDQZAzmfEcdH2Vp2gRcyfZX2yaVSoybmfKVQ+PGSC00P53O3v6GH7Cj+fSpknOTImsUxYfhViad1bkC0k9lRmOMff9RBbTE+2JiYsoed/bRZ6bkFM81HI/aI4CLW0z0dEogHJVe6osT6nRDUNzS4inXR4ekfhlgp4BgI2/6/wyg5kBfXq9uSYVvtZw2wi2svqlLTKvzuUwvKxOoK2e5TL4aXeRPLA5S874+hrYrnC6hGF6cMwKV/d/ehCh7KiKM6T9tt4Yfvt6kxWORxtuH00dTJhu9RvJtEB5o4Rujhh5+k0a+BghYXjhjQu+XFl1jLom7LQpION7xvy2g31cBgyHxd6S1pT6JZyuQY0A4H4f5NlHxrkLWPehdSKFyk86aBANVxXPCOheNG7LgAKO6D2knTt8diCRzcSzTG2xWDBObc=
    on_success: always
