language: node_js
node_js:
- '6'
- '4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  slack:
    secure: rkRKwcJxh2Bc2yEZ092+rbBcJ1lKS5wjMaIyBnpQ3P4bVInOm1WmfG79CQnZHFeJEzVwoOBlr2Ko7HaHdbxa9aa7WXTuHGRMvcyagYGuxJT7cLhBjxeUSpHsWlKffoMnO0Xx6ztgNYrOVXW382ImuNO9Bu0pa8P4K4uD942bekaqKRH2HV+SmNj6Tz+dvBPfFddxPBNQ8cyUDY7sEoMkozCZMfT+hLxAVUoqWJ3/IoL+Bgg4NNdOQyAu0Z9XVmVRqWcAG6g98Tl6VGITaTBPTTgBOqs5MgWs/YdOEE2dkEK+OEQj3sME5e9iuOaV/fkMsGYMH4NTIJZIRNigO1ortkYDTai/Ftibxe31VlrIHFHqPJ1Z4LIIOhzCJFJfVymwR7N7SFFwOlBWxn9d2bTSTaqQMDnW5Rnlz3uc85KwbH4xUgX1MVh3Naj3t2K3+1g7xuac6PoyxSIGp21bPydLcYZ5ZOO49iKkvo23aZq4Kbp+ZuYntyshNkUcZsMEP2eTwOCpr0c7mdIJgEfQx0B/gfm+Ksa1FuRhJlkLkbL9Nm4NzVeTwVZjTgH8NkTsHaAVN6TnWHESNKlFtCR/lHjW80AtOMTzJZXwRn5lzKrUQmspsNkIZP/n3Qn3fUwXHACIkAb4bY1hGaUBHd74Pd4Azb0Y2dUdFp0cc7yPP5GsEaA=
deploy:
  provider: npm
  email: thomas.conner@me.com
  api_key:
    secure: OKvKR6ONH2oJWUDMrPHDFIbXn1ZBFa+HKAQvqxIHjg2F9gctgKtiUS+CBfb7RYieCbOmvK5rFN490+0hSMt988GpEBidttIgzeEuFcVZn/t0TZhRPjUq8wIKtPUBeC4Q1ybjKDsj75SmDKgQzOksBptBd1LPVQ3o568CdQ65ENldw+cvZyo3/2BnQvcS4v2zzC5XRg5SkWm+ENSiOCVJhVofuFIFHmm4xi4VdHKE26tSOAchj+YNF7j917nVO9dyzitN3CB5LbAT8TUGyaAV4zudVqAkCdExyho23poDY4ttE5SG9nBghPAqKMWvMcVNHlvGRkeCkfy8ZvfVq9PWTPo/j1v0nri8lJDiQvKYEU2U0+ryqY1Su9CzMR0Lapt17cqG4RYbL8+nG13nYYTkDzeWgwQkTP92z+5gFFuC5oes7cxgaANRES31u58wTHVb/WLuLfakzLKM4po5XfDjz7sTELKMCXLk+v9pXMeGsT5KMaa96vcvAAqKBdb5dRAhWDctRGHlZR++ZttDrNnbt2boTDNd8c/kABSC/qbz+UrPB0C3QqgEKANKQcoP5svUO6bY3y6l1JkxwbBGToX+g5JIsdcZBaX2nOGR+G8xNjtk6lsYPl5e1nKQm14dXIBSYZNFzB9dki9A3lJYSffGbXhYqI3ByiM5g6/LJDVkCZU=
  on:
    tags: true
    repo: Kinvey/javascript-sdk-core
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate < coverage/lcov.info
