env:
  global:
    - INTEGRATION_TESTS_NODEJS_VERSION='8.1.0'
    - INTEGRATION_TESTS_NATIVESCRIPT_VERSION='3.4.2'
    - INTEGRATION_TESTS_CORDOVA_VERSION='8.0.0'
    - UNIT_TESTS_NODEJS_VERSION='9'
    - RUN_INTEGRATION_TESTS_FILE_LOCATION='./test/integration/run-tests'
    - FACEBOOK_EMAIL='system.everlive@gmail.com'
    - FACEBOOK_PASSWORD='test_pass'

matrix:
  include:


    - os: linux
      env: PLATFORM='HTML5'
      language: node_js
      node_js: ${INTEGRATION_TESTS_NODEJS_VERSION}
      sudo: enabled
      script: 
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform html5

