language: node_js
node_js:
  - '6'
addons:
  code_climate:
    repo_token:
      secure: pjnl2IGK7W+EceE50hoqKKvO6389gUY7dOmT5eUEeCQd1hruM7/Qc09YDLWsxyCC/MNEZYJK/7EclL1lhTDaVgjgMv890RLUaN+kJrQuKS7mJTiXknXiF6x5yDrtukatJTw0dFrkyCnmJaxrJiKZp8CcuuE4FZ9UsklU/VPf+CZ91oJF+IBtBQYpxO7D1pWIrH4MIBj5Vj9EcO2QYl2lOqT18uSMuMwBrBH8dI4cRUYvw2Wf7nDOyQYqS1YB3kEejD7cHHYX+vJ1QDT2ikAf4ds3W0K3l4oc6krjgVPwvUV8LoyZvXuhacLw6lS7a47vqHhjQ+nhiVOydoQA7B6lYsK0iTMKomW6A1gvGAI8VdWuDYLF9p6Fu1SigkZUW6px0Le4W8XvOjLgm2TNAYnzRujfDDticUvafep3WlOYijj/LRmD2KCXOxtaaG0SCmNy6ox6rBzIOMWr9y8dita/AKnW5cxHRCtPFAVLugFVZoZ7kEds2/b5Y+KCMy7Bl/RcLQuVJOoTuiQASPE33p618QiwGY+TD0dR+Kj+9SvRy4p8oYDOQLuy8SuMx3gAGmyy5Kg2wQ6Ng1DmKWm0xGWx+PjgYHUR/Mxbpt/cAc2AlMp7w5xClUgAyTuJsTsW0sK5fBpULEyZARRlNHnYl50XaqY6B1b2+M1Gg1stdGEmanA=
deploy:
  provider: npm
  email: thomas.conner@me.com
  api_key:
    secure: OKvKR6ONH2oJWUDMrPHDFIbXn1ZBFa+HKAQvqxIHjg2F9gctgKtiUS+CBfb7RYieCbOmvK5rFN490+0hSMt988GpEBidttIgzeEuFcVZn/t0TZhRPjUq8wIKtPUBeC4Q1ybjKDsj75SmDKgQzOksBptBd1LPVQ3o568CdQ65ENldw+cvZyo3/2BnQvcS4v2zzC5XRg5SkWm+ENSiOCVJhVofuFIFHmm4xi4VdHKE26tSOAchj+YNF7j917nVO9dyzitN3CB5LbAT8TUGyaAV4zudVqAkCdExyho23poDY4ttE5SG9nBghPAqKMWvMcVNHlvGRkeCkfy8ZvfVq9PWTPo/j1v0nri8lJDiQvKYEU2U0+ryqY1Su9CzMR0Lapt17cqG4RYbL8+nG13nYYTkDzeWgwQkTP92z+5gFFuC5oes7cxgaANRES31u58wTHVb/WLuLfakzLKM4po5XfDjz7sTELKMCXLk+v9pXMeGsT5KMaa96vcvAAqKBdb5dRAhWDctRGHlZR++ZttDrNnbt2boTDNd8c/kABSC/qbz+UrPB0C3QqgEKANKQcoP5svUO6bY3y6l1JkxwbBGToX+g5JIsdcZBaX2nOGR+G8xNjtk6lsYPl5e1nKQm14dXIBSYZNFzB9dki9A3lJYSffGbXhYqI3ByiM5g6/LJDVkCZU=
  on:
    tags: true
    repo: Kinvey/javascript-sdk-core
notifications:
  slack:
    secure: rkRKwcJxh2Bc2yEZ092+rbBcJ1lKS5wjMaIyBnpQ3P4bVInOm1WmfG79CQnZHFeJEzVwoOBlr2Ko7HaHdbxa9aa7WXTuHGRMvcyagYGuxJT7cLhBjxeUSpHsWlKffoMnO0Xx6ztgNYrOVXW382ImuNO9Bu0pa8P4K4uD942bekaqKRH2HV+SmNj6Tz+dvBPfFddxPBNQ8cyUDY7sEoMkozCZMfT+hLxAVUoqWJ3/IoL+Bgg4NNdOQyAu0Z9XVmVRqWcAG6g98Tl6VGITaTBPTTgBOqs5MgWs/YdOEE2dkEK+OEQj3sME5e9iuOaV/fkMsGYMH4NTIJZIRNigO1ortkYDTai/Ftibxe31VlrIHFHqPJ1Z4LIIOhzCJFJfVymwR7N7SFFwOlBWxn9d2bTSTaqQMDnW5Rnlz3uc85KwbH4xUgX1MVh3Naj3t2K3+1g7xuac6PoyxSIGp21bPydLcYZ5ZOO49iKkvo23aZq4Kbp+ZuYntyshNkUcZsMEP2eTwOCpr0c7mdIJgEfQx0B/gfm+Ksa1FuRhJlkLkbL9Nm4NzVeTwVZjTgH8NkTsHaAVN6TnWHESNKlFtCR/lHjW80AtOMTzJZXwRn5lzKrUQmspsNkIZP/n3Qn3fUwXHACIkAb4bY1hGaUBHd74Pd4Azb0Y2dUdFp0cc7yPP5GsEaA=
after_script:
  - npm run cover
  - codeclimate-test-reporter < coverage/lcov.info
