env:
  global:
    - INTEGRATION_TESTS_NODEJS_VERSION='8.1.0'
    - INTEGRATION_TESTS_NATIVESCRIPT_VERSION='3.4.2'
    - INTEGRATION_TESTS_CORDOVA_VERSION='8.0.0'
    - UNIT_TESTS_NODEJS_VERSION='9'
    - RUN_INTEGRATION_TESTS_FILE_LOCATION='./test/integration/run-tests'
    - secure: IuywIkmD6t8wxh1OpjMgHvvGIzDBDXXahkhlTFsuxN0kowqlWrF9F1gCyMdg7dALJ+rtInISGIm+7UrTbyoNSBPHRkzXyU0p1eDx8shBLYOg8dKxTwUn61zb3ckOMt1sYwOy2x00d6MUIayB0uu5haYUyi4zt8bqs2Mp548oO4r5+Y4/Tnt3lP5/dGFyxOER7HZdb+Ka9KguzhgJeWSF7dRMjQCHCccUO4i2Gp6cQVE8xI2e9nN6SXDwuQrIq8zRcbCh/5sH4R1uEHEKDT5u0gBIN5eBQSkjG7rtBi3Vaif7TsSqRTGUV2njKCIO7Cd8HLHeY9D7WHFMsLXOGo2hGZvdaeq9QXoJ3mswNO0AUP6Smam+Bg8YeHy+x6+/yGIT7N0J0wrZUY3WeEpq3b14+f2YtDhhGS0m3K6uLllOQ+NVHvkgEEVp7y4pxJhTf8e9Gc6ZCoJOAY+NCjI7wnDQ0DbyanoE5JbhyL6oDv1P+sZE9Ixm3fRIZVrUf4g3P31AXL4O4UUdcTjMwUmTktweXGLCKqbtS/XepxtaeUTthacoTYALkjpgDeB3jrOLiEUxVjI2GYH4IRjdutAohVfgEFy8m5KiTdw5pQQFzT+u+T+YRf9N3o5O/BSSJuzpa57nmPa9ShCHNLLahEAVi65fRo1Ols7pU8ZnLxZ7r6PrrwQ=
    - secure: ConvbHNWuW4iMz/8vS2Gwe/lipCcC+JgmVz/baXvsH8CP/fw4PcWbXyYmCq9uVcibernp21AD3vzwy00f2sbG/gDa4uGW4FE0L87Pl+lbKoQeBPBvSVvt2rWFGJc1wuXbxwgTRJT3KGXgDFFOQGtwGWjvqT2ScTwKxeNuMICA7h5PPvTrVwO1NatKoLXz+kh/+9+mXuCTU1nfOvfH7qFWxSE19wKoNOe8xRdeCAb0GcHthp9jbxqW5gOBcIjv/7Fu7yGwUx1+khx3v4QtCiQxytr0GooiBSssogmYTyueFp+jOwY2c2+2rzwhtWBHWFq+kOdIs53heq4ccs1Nnb3j00THToxnelpA/kC2JF6lEuPyjnAeZoatEbGicsWiDMCmBOtAtNTIsfNbBKu53MMag6KHbtDMLL+Ma5DTzzQgkr58k/bZzVlPZkMShiKHaHPBdhTflIm1X0moHmO3rinMJN3MAT9TtmVBD2KJcF/a6S9ULsQEZG/GMLzaTCorf8Qo+dSL4+B3S7QEkZSJQw8MGczvPqATnxA8hOMzQpP3HuVxXAu+ZoTF9tybo4v4i2yPe9imIPnhoRYz1JjNGQZ0XenNRh3vQyuTs/tlB9CyVKCqZYzeNwvuI6aSVi4egEUuTEOdqW+vCKoGdypLVskiuibNvAQxmPX0bx7qGKtDc0=

matrix:
  include:


    - os: linux
      env: PLATFORM='HTML5'
      language: node_js
      node_js: ${INTEGRATION_TESTS_NODEJS_VERSION}
      sudo: enabled
      script: 
        - node ${RUN_INTEGRATION_TESTS_FILE_LOCATION} --platform html5

