name: 'nativescript -> npm'

on:
  workflow_dispatch:

env:
  NPM_TAG: 'next'

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup
        run: npm i --ignore-scripts --legacy-peer-deps --no-package-lock

      - name: Generate Version
        run: |
          echo NPM_VERSION=$(node -e "console.log(require('./package.json').version);") >> $GITHUB_ENV

      - name: Bump Version
        run: npm version $NPM_VERSION

      - name: Build nativescript
        run: npm pack

      - name: Publish nativescript
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "Publishing nativescript@$NPM_VERSION to NPM with tag $NPM_TAG..."
          npm publish akylas-nativescript-cli-$NPM_VERSION.tgz --tag $NPM_TAG
